# robot base coordinate, unit meter
# [x, y]
xy1: [0.3, -0.1]
xy2: [0.5, 0.2]
xy3: [0.3, 0.2]
xy4: [0.5, -0.1]
# camera base coordinate
# [col, row]
uv1: [681,194]
uv2: [903, 341]
uv3: [903,195]
uv4: [677,335]
